#!/bin/sh
#
# @name Solar-Blimp
#
# @type Blimp
# @class Plane
#
# @output AUX1 Motor 1
# @output AUX2 Motor 2
# @output AUX3 Motor 3
# @output AUX4 Servo motor for rotor 2 and 3 arm
#
# @maintainer Patrick Lodes <patrick.lodes@zae-bayern.de>
#

sh /etc/init.d/rc.fw_defaults

#Parameters here:
if [ $AUTOCNF = yes ]
then
	# Set parameters here

	param set PWM_AUX_DISARMED 1000

	param set PWM_AUX_MIN 1100

	param set PWM_AUX_MAX 2000

fi

# Set the frame type.
# Configure this as Airship
set MAV_TYPE 7

# Set mixer
set MIXER skip
set MIXER_AUX solar_blimp

set PWM_OUT 1234
